-----THIS IS A SIMPLE LOG FILE-----
[ERROR][9 / 12 / 2104][18 : 37 : 58] : Connection refused : connect()
